server:
  port: 8088 #设置项目访问端口
  servlet: 
    context-path: /JOJO   #设置项目访问的根路径
  
logback:
   logdir: G://logs #日志的输出目录
   appname: PanaceaProject #日志的项目名称
   
#是否开启swagger
swagger:
   show: true
   
spring:
  main:    allow-bean-definition-overriding: true  #启动时报错-同名的bean注入问题，加上这个配置就好了
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          #配置指明在程序启动的时候要删除并且创建实体类对应的表。这个参数很危险，因为他会把对应的
          #表删除掉然后重建。所以千万不要在生成环境中使用。只有在测试环境中，一开始初始化数据库结
          #构的时候才能使用一次。
          #create----每次运行该程序，没有表格会新建表格，表内有数据会清空
          #drop----每次程序结束的时候会清空表
          #update----每次运行程序，没有表格会新建表格，表内有数据不会清空，只会更新，表名变了不会删除表，会生成新表
          #validate----运行程序会校验数据与数据库的字段类型是否相同，不同会报错
          auto: update 
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect #这个参数是在建表的时候，将默认的存储引擎切换为 InnoDB 用的    show-sql: true #配置在日志中打印出执行的 SQL 语句信息
    
